### ISSUE TITLE
pip installation fails on macOS Mojave

### ISSUE THREAD

**Issue by mrapacz** [src-d/wmd-relax#54] opened 2019-05-31 16:57 UTC
Hello there!

I tried running 
```
pip install wmd
``` 
as specified in the README. The package build fails for me with the following error message though:
```
$ pip install wmd
Collecting wmd
  Using cached https://files.pythonhosted.org/packages/4b/0d/0b4915c61163b00c87eb9f4e4ea5e96dd5bfdaf375f6571df9245ecf2c3a/wmd-1.3.1.tar.gz
Requirement already satisfied: numpy in /anaconda3/envs/seed/lib/python3.7/site-packages (from wmd) (1.16.2)
Building wheels for collected packages: wmd
  Building wheel for wmd (setup.py) ... error
  ERROR: Complete output from command /anaconda3/envs/seed/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/1x/ym7vbph10fb6hnz0wygkm7_m0000gn/T/pip-install-nrj8xc17/wmd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/1x/ym7vbph10fb6hnz0wygkm7_m0000gn/T/pip-wheel-7osdgixc --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/wmd
  copying wmd/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/wmd
  running build_ext
  building 'libwmdrelax' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/or-tools
  creating build/temp.macosx-10.7-x86_64-3.7/or-tools/src
  creating build/temp.macosx-10.7-x86_64-3.7/or-tools/src/graph
  creating build/temp.macosx-10.7-x86_64-3.7/or-tools/src/base
  creating build/temp.macosx-10.7-x86_64-3.7/or-tools/src/util
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/seed/include -arch x86_64 -I/anaconda3/envs/seed/include -arch x86_64 -I/anaconda3/envs/seed/lib/python3.7/site-packages/numpy/core/include -Ior-tools/src -I/anaconda3/envs/seed/include/python3.7m -c python.cc -o build/temp.macosx-10.7-x86_64-3.7/python.o -std=c++11 -march=native -ftree-vectorize -DNDEBUG -Wno-sign-compare -fPIC -flto
  warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  python.cc:3:10: fatal error: 'memory' file not found
  #include <memory>
           ^~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for wmd
  Running setup.py clean for wmd
Failed to build wmd
Installing collected packages: wmd
  Running setup.py install for wmd ... error
    ERROR: Complete output from command /anaconda3/envs/seed/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/1x/ym7vbph10fb6hnz0wygkm7_m0000gn/T/pip-install-nrj8xc17/wmd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/1x/ym7vbph10fb6hnz0wygkm7_m0000gn/T/pip-record-amkzs5dm/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/wmd
    copying wmd/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/wmd
    running build_ext
    building 'libwmdrelax' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/or-tools
    creating build/temp.macosx-10.7-x86_64-3.7/or-tools/src
    creating build/temp.macosx-10.7-x86_64-3.7/or-tools/src/graph
    creating build/temp.macosx-10.7-x86_64-3.7/or-tools/src/base
    creating build/temp.macosx-10.7-x86_64-3.7/or-tools/src/util
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/envs/seed/include -arch x86_64 -I/anaconda3/envs/seed/include -arch x86_64 -I/anaconda3/envs/seed/lib/python3.7/site-packages/numpy/core/include -Ior-tools/src -I/anaconda3/envs/seed/include/python3.7m -c python.cc -o build/temp.macosx-10.7-x86_64-3.7/python.o -std=c++11 -march=native -ftree-vectorize -DNDEBUG -Wno-sign-compare -fPIC -flto
    warning: include path for stdlibc++ headers not found; pass '-stdlib=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    python.cc:3:10: fatal error: 'memory' file not found
    #include <memory>
             ^~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command "/anaconda3/envs/seed/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/1x/ym7vbph10fb6hnz0wygkm7_m0000gn/T/pip-install-nrj8xc17/wmd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/1x/ym7vbph10fb6hnz0wygkm7_m0000gn/T/pip-record-amkzs5dm/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/1x/ym7vbph10fb6hnz0wygkm7_m0000gn/T/pip-install-nrj8xc17/wmd/
```

I'm using macOS Mojave 10.14.5. As you can also tell from the error message, I'm running a conda environment with Python 3.7:
```bash
$ pip --version
pip 19.1.1 from /anaconda3/envs/seed/lib/python3.7/site-packages/pip (python 3.7)
$ python --version
Python 3.7.3
```

Do you have an idea how I could fix this issue? 
Is there maybe some external dependency I need to have on my mac? I didn't see anything mentioned in the readme. 
Will be grateful for any help, thanks!

**Comment by vmarkovtsev** [comment] 2019-05-31 17:16
Hi @mrapacz I see that you are using Anaconda. This environment is officially not supported, and will never be. Thus I am closing the issue.

Sorry!

**Closed by vmarkovtsev** 2019-05-31 17:16 UTC

**Comment by wuxxx949** [comment] 2019-06-25 21:10
Solved this issue by 
```
CFLAGS=-stdlib=libc++ pip install wmd==1.3.1
```
The problem is that stdlibc++ is deprecated by Mojave. It's nothing to do with Anaconda.

**Comment by vmarkovtsev** [comment] 2019-06-26 05:47
As suggested in https://github.com/src-d/wmd-relax/issues/5#issuecomment-371127046
